-- Enum Type merge script

MERGE INTO authDataSource_dev.ENUMTYPEREF tar USING (
SELECT 3 AS ads_ID, '9CE7161A-0ABC-0041-838E-382FCC81DC69' AS ads_UUID, 'colorPrimary' AS ENUM_TYPE, 'Internet' AS ads_Src_Name, 'v0.0.0' AS ads_Src_Version, 'List the the 3 primary colors.' AS ENUM_TYPE_DESC FROM dual 
) src ON ( tar.ENUM_TYPE = src.ENUM_TYPE ) WHEN MATCHED THEN      UPDATE SET tar.ads_ID = src.ads_ID, tar.ads_UUID = src.ads_UUID, tar.ENUM_TYPE_DESC = src.ENUM_TYPE_DESC, tar.ads_Src_Name = src.ads_Src_Name, tar.ads_Src_Version = src.ads_Src_Version WHEN NOT MATCHED THEN   INSERT ( tar.ENUM_TYPE, tar.ENUM_TYPE_DESC, tar.ads_Src_Name, tar.ads_Src_Version )     VALUES ( src.ENUM_TYPE, src.ENUM_TYPE_DESC, src.ads_Src_Name, src.ads_Src_Version ); 

COMMIT;


-- Enum Value merge script

MERGE INTO authDataSource_dev.ENUMVALUEREF tar USING ( 
SELECT 'colorPrimary' AS ENUM_TYPE, 'RED' AS ENUM_VALUE, 'Red' AS ENUM_DISPLAY_NAME, 3 AS ENUM_TYPE_REC_ID, '9CE7161A-0ABC-0041-838E-382FCC81DC69' AS ENUM_TYPE_REC_UUID, 0 AS ORDER_BY, 'N' AS CONSTANT_FLAG, '202' AS  REC_ID, '40F2953E-518E-7B45-A5A7-52FD2B3EFFF2' AS REC_UUID, 'Red' AS DESCRIPTION FROM dual UNION ALL 
SELECT 'colorPrimary' AS ENUM_TYPE, 'YELLOW' AS ENUM_VALUE, 'Yellow' AS ENUM_DISPLAY_NAME, 3 AS ENUM_TYPE_REC_ID, '9CE7161A-0ABC-0041-838E-382FCC81DC69' AS ENUM_TYPE_REC_UUID, 0 AS ORDER_BY, 'N' AS CONSTANT_FLAG, '203' AS  REC_ID, '579C86A8-43A7-F24F-88BA-F6C712F7A43D' AS REC_UUID, 'Yellow' AS DESCRIPTION FROM dual UNION ALL 
SELECT 'colorPrimary' AS ENUM_TYPE, 'BLUE' AS ENUM_VALUE, 'Blue' AS ENUM_DISPLAY_NAME, 3 AS ENUM_TYPE_REC_ID, '9CE7161A-0ABC-0041-838E-382FCC81DC69' AS ENUM_TYPE_REC_UUID, 0 AS ORDER_BY, 'N' AS CONSTANT_FLAG, '204' AS  REC_ID, '90194E7B-ACDE-DA49-BA62-F4D0B569AA5D' AS REC_UUID, 'Blue' AS DESCRIPTION FROM dual
) src
ON ( tar.ENUM_TYPE = src.ENUM_TYPE  AND tar.ENUM_VALUE = src.ENUM_VALUE ) 
WHEN MATCHED THEN 
    UPDATE SET tar.ENUM_DISPLAY_NAME = src.ENUM_DISPLAY_NAME, tar.DESCRIPTION = src.DESCRIPTION, tar.ENUM_TYPE_REC_ID = src.ENUM_TYPE_REC_ID, tar.ENUM_TYPE_REC_UUID = src.ENUM_TYPE_REC_UUID, tar.ORDER_BY = src.ORDER_BY, tar.CONSTANT_FLAG  = src.CONSTANT_FLAG, tar.REC_ID  = src.REC_ID, tar.REC_UUID  = src.REC_UUID  
WHEN NOT MATCHED THEN 
    INSERT ( tar.ENUM_TYPE, tar.ENUM_VALUE, tar.ENUM_DISPLAY_NAME, tar.DESCRIPTION, tar.ENUM_TYPE_REC_ID, tar.ENUM_TYPE_REC_UUID, tar.ORDER_BY, tar.CONSTANT_FLAG ) 
    VALUES ( src.ENUM_TYPE, src.ENUM_VALUE, src.ENUM_DISPLAY_NAME, src.DESCRIPTION, src.ENUM_TYPE_REC_ID, src.ENUM_TYPE_REC_UUID, src.ORDER_BY, src.CONSTANT_FLAG );

COMMIT;

