

-- Enum Type merge script
MERGE INTO authDataSource_dev.ENUMTYPEREF tar USING (
SELECT 2 AS REC_ID, 'E71AB723-4D43-7248-8769-96FF4059B604' AS REC_UUID, 'ads_source' AS ENUM_TYPE, 'NA' AS SOURCE_NAME, '0.0.0' AS SOURCE_VERSION, 'Authoritative Data Source (ADS) - DoD 8320.2: A source of data or information that is recognized by members of a Community of Interest (COI) to be valid or trusted because it is considered to be highly reliable or accurate or is from an official publication or reference (e.g., the United States (U.S.) Postal Service is the official source of U.S. mailing ZIP codes). ' AS ENUM_TYPE_DESC FROM dual 
) src ON ( tar.ENUM_TYPE = src.ENUM_TYPE ) WHEN MATCHED THEN      UPDATE SET tar.ADS_ID = src.REC_ID, tar.ADS_UUID = src.REC_UUID, tar.ENUM_TYPE_DESC = src.ENUM_TYPE_DESC, tar.ADS_SRC_NAME = src.SOURCE_NAME, tar.ADS_SRC_VERSION = src.SOURCE_VERSION WHEN NOT MATCHED THEN   INSERT ( tar.ENUM_TYPE, tar.ENUM_TYPE_DESC, tar.ADS_SRC_NAME, tar.ADS_SRC_VERSION )     VALUES ( src.ENUM_TYPE, src.ENUM_TYPE_DESC, src.SOURCE_NAME, src.SOURCE_VERSION ); 

COMMIT;
-- Enum Value merge script

MERGE INTO authDataSource_dev.ENUMVALUEREF tar 
USING (  
SELECT 'ads_source' AS ENUM_TYPE, 'PRDS_V3.0.0' AS ENUM_VALUE, 'Purchase Request Data Standard (PRDS) v3.0.0' AS ENUM_DISPLAY_NAME, 2 AS ENUM_TYPE_REC_ID, 'E71AB723-4D43-7248-8769-96FF4059B604' AS ENUM_TYPE_REC_UUID, 10 AS ORDER_BY, 'N' AS CONSTANT_FLAG, '192' AS  REC_ID, 'CF3E1E02-E7F3-6F4A-BC29-A4FECD67D158' AS REC_UUID, 'The Purchase Request Data Standard (PRDS) is based on and designed to be congruent with the Procurement Data Standard (PDS). Much like the PDS, the PRDS represents an entire purchase request as discretely identifiable data elements in an XML structure. In addition to the necessary data on a purchase request, the PRDS is capable of transmitting the additional pieces of data found in a Military Interdepartmental Purchase Request (MIPR, DD form 448), the MIPR Acceptance (DD-448-2), and other inter/intra-governmental transactions (IGT).' AS DESCRIPTION FROM dual UNION ALL 
SELECT 'ads_source' AS ENUM_TYPE, 'PRDS_V2.0.0' AS ENUM_VALUE, 'Purchase Request Data Standard (PRDS) v2.0.0' AS ENUM_DISPLAY_NAME, 2 AS ENUM_TYPE_REC_ID, 'E71AB723-4D43-7248-8769-96FF4059B604' AS ENUM_TYPE_REC_UUID, 20 AS ORDER_BY, 'N' AS CONSTANT_FLAG, '193' AS  REC_ID, '5A6C588B-D568-164C-A1EF-938E0416D975' AS REC_UUID, 'The Purchase Request Data Standard (PRDS) is based on and designed to be congruent with the Procurement Data Standard (PDS). Much like the PDS, the PRDS represents an entire purchase request as discretely identifiable data elements in an XML structure. In addition to the necessary data on a purchase request, the PRDS is capable of transmitting the additional pieces of data found in a Military Interdepartmental Purchase Request (MIPR, DD form 448), the MIPR Acceptance (DD-448-2), and other inter/intra-governmental transactions (IGT).' AS DESCRIPTION FROM dual UNION ALL 
SELECT 'ads_source' AS ENUM_TYPE, 'PRDS_V1.1.0' AS ENUM_VALUE, 'Purchase Request Data Standard (PRDS) v1.1.0' AS ENUM_DISPLAY_NAME, 2 AS ENUM_TYPE_REC_ID, 'E71AB723-4D43-7248-8769-96FF4059B604' AS ENUM_TYPE_REC_UUID, 30 AS ORDER_BY, 'N' AS CONSTANT_FLAG, '194' AS  REC_ID, 'FD96A70B-C1B0-8449-BD72-997C33D67315' AS REC_UUID, 'The Purchase Request Data Standard (PRDS) is based on and designed to be congruent with the Procurement Data Standard (PDS). Much like the PDS, the PRDS represents an entire purchase request as discretely identifiable data elements in an XML structure. In addition to the necessary data on a purchase request, the PRDS is capable of transmitting the additional pieces of data found in a Military Interdepartmental Purchase Request (MIPR, DD form 448), the MIPR Acceptance (DD-448-2), and other inter/intra-governmental transactions (IGT).' AS DESCRIPTION FROM dual UNION ALL 
SELECT 'ads_source' AS ENUM_TYPE, 'PRDS_V1.0.2' AS ENUM_VALUE, 'Purchase Request Data Standard (PRDS) v1.0.2' AS ENUM_DISPLAY_NAME, 2 AS ENUM_TYPE_REC_ID, 'E71AB723-4D43-7248-8769-96FF4059B604' AS ENUM_TYPE_REC_UUID, 40 AS ORDER_BY, 'N' AS CONSTANT_FLAG, '195' AS  REC_ID, '3F0652E4-E9A2-3B49-8182-C9B6A22B4CFB' AS REC_UUID, 'The Purchase Request Data Standard (PRDS) is based on and designed to be congruent with the Procurement Data Standard (PDS). Much like the PDS, the PRDS represents an entire purchase request as discretely identifiable data elements in an XML structure. In addition to the necessary data on a purchase request, the PRDS is capable of transmitting the additional pieces of data found in a Military Interdepartmental Purchase Request (MIPR, DD form 448), the MIPR Acceptance (DD-448-2), and other inter/intra-governmental transactions (IGT).' AS DESCRIPTION FROM dual UNION ALL 
SELECT 'ads_source' AS ENUM_TYPE, 'PRDS_V1.0.1' AS ENUM_VALUE, 'Purchase Request Data Standard (PRDS) v1.0.1' AS ENUM_DISPLAY_NAME, 2 AS ENUM_TYPE_REC_ID, 'E71AB723-4D43-7248-8769-96FF4059B604' AS ENUM_TYPE_REC_UUID, 50 AS ORDER_BY, 'N' AS CONSTANT_FLAG, '196' AS  REC_ID, 'C5E999B2-5051-D541-BE69-233F541B265F' AS REC_UUID, 'The Purchase Request Data Standard (PRDS) is based on and designed to be congruent with the Procurement Data Standard (PDS). Much like the PDS, the PRDS represents an entire purchase request as discretely identifiable data elements in an XML structure. In addition to the necessary data on a purchase request, the PRDS is capable of transmitting the additional pieces of data found in a Military Interdepartmental Purchase Request (MIPR, DD form 448), the MIPR Acceptance (DD-448-2), and other inter/intra-governmental transactions (IGT).' AS DESCRIPTION FROM dual UNION ALL 
SELECT 'ads_source' AS ENUM_TYPE, 'PDS_PhaseII_V2.5.1' AS ENUM_VALUE, 'Procurement Data Standard (PDS) Phase II v2.5.1' AS ENUM_DISPLAY_NAME, 2 AS ENUM_TYPE_REC_ID, 'E71AB723-4D43-7248-8769-96FF4059B604' AS ENUM_TYPE_REC_UUID, 10 AS ORDER_BY, 'N' AS CONSTANT_FLAG, '198' AS  REC_ID, 'A5793C2B-520C-8240-82BE-0773C18D1C17' AS REC_UUID, 'The Procurement Data Standard (PDS) is a system-agnostic data standard that is adopting and implemented DoD-wide for creation, translation, processing, and sharing of procurement actions. It defines the minimum requirements for contract writing system output to improve visibility and accuracy of contract-related data, to support interoperability of DoD acquisition systems and to standardize and streamline the procure-to-pay business process. Further, the PDS will improve visibility of contract-related data, enabling senior DoD leadership to make better informed business decisions. And finally, this data standard will support future migration to enterprise and federal systems and processes where appropriate.' AS DESCRIPTION FROM dual UNION ALL 
SELECT 'ads_source' AS ENUM_TYPE, 'PDS_PhaseII_V2.5.0' AS ENUM_VALUE, 'Procurement Data Standard (PDS) Phase II v2.5.0' AS ENUM_DISPLAY_NAME, 2 AS ENUM_TYPE_REC_ID, 'E71AB723-4D43-7248-8769-96FF4059B604' AS ENUM_TYPE_REC_UUID, 20 AS ORDER_BY, 'N' AS CONSTANT_FLAG, '199' AS  REC_ID, 'E01A140A-0A14-2A4A-9C25-7F13173533BB' AS REC_UUID, 'The Procurement Data Standard (PDS) is a system-agnostic data standard that is adopting and implemented DoD-wide for creation, translation, processing, and sharing of procurement actions. It defines the minimum requirements for contract writing system output to improve visibility and accuracy of contract-related data, to support interoperability of DoD acquisition systems and to standardize and streamline the procure-to-pay business process. Further, the PDS will improve visibility of contract-related data, enabling senior DoD leadership to make better informed business decisions. And finally, this data standard will support future migration to enterprise and federal systems and processes where appropriate.' AS DESCRIPTION FROM dual UNION ALL 
SELECT 'ads_source' AS ENUM_TYPE, 'PDS_PhaseII_V2.4.0' AS ENUM_VALUE, 'Procurement Data Standard (PDS) Phase II v2.4.0' AS ENUM_DISPLAY_NAME, 2 AS ENUM_TYPE_REC_ID, 'E71AB723-4D43-7248-8769-96FF4059B604' AS ENUM_TYPE_REC_UUID, 30 AS ORDER_BY, 'N' AS CONSTANT_FLAG, '200' AS  REC_ID, 'EE947B23-927D-9B48-8BDE-8D042D05A190' AS REC_UUID, 'The Procurement Data Standard (PDS) is a system-agnostic data standard that is adopting and implemented DoD-wide for creation, translation, processing, and sharing of procurement actions. It defines the minimum requirements for contract writing system output to improve visibility and accuracy of contract-related data, to support interoperability of DoD acquisition systems and to standardize and streamline the procure-to-pay business process. Further, the PDS will improve visibility of contract-related data, enabling senior DoD leadership to make better informed business decisions. And finally, this data standard will support future migration to enterprise and federal systems and processes where appropriate.' AS DESCRIPTION FROM dual UNION ALL 
SELECT 'ads_source' AS ENUM_TYPE, 'PDS_PhaseII_V2.3.0' AS ENUM_VALUE, 'Procurement Data Standard (PDS) Phase II v2.3.0' AS ENUM_DISPLAY_NAME, 2 AS ENUM_TYPE_REC_ID, 'E71AB723-4D43-7248-8769-96FF4059B604' AS ENUM_TYPE_REC_UUID, 40 AS ORDER_BY, 'N' AS CONSTANT_FLAG, '201' AS  REC_ID, '7AFB8033-52C4-A044-ACD0-BAA34DFD2FA2' AS REC_UUID, 'The Procurement Data Standard (PDS) is a system-agnostic data standard that is adopting and implemented DoD-wide for creation, translation, processing, and sharing of procurement actions. It defines the minimum requirements for contract writing system output to improve visibility and accuracy of contract-related data, to support interoperability of DoD acquisition systems and to standardize and streamline the procure-to-pay business process. Further, the PDS will improve visibility of contract-related data, enabling senior DoD leadership to make better informed business decisions. And finally, this data standard will support future migration to enterprise and federal systems and processes where appropriate.' AS DESCRIPTION FROM dual UNION ALL 
SELECT 'ads_source' AS ENUM_TYPE, 'PRDS_V1.0.0' AS ENUM_VALUE, 'Purchase Request Data Standard (PRDS) v1.0.0' AS ENUM_DISPLAY_NAME, 2 AS ENUM_TYPE_REC_ID, 'E71AB723-4D43-7248-8769-96FF4059B604' AS ENUM_TYPE_REC_UUID, 60 AS ORDER_BY, 'N' AS CONSTANT_FLAG, '197' AS  REC_ID, '3BE490E2-EF8D-9E46-AB67-3572F97B638C' AS REC_UUID, 'The Purchase Request Data Standard (PRDS) is based on and designed to be congruent with the Procurement Data Standard (PDS). Much like the PDS, the PRDS represents an entire purchase request as discretely identifiable data elements in an XML structure. In addition to the necessary data on a purchase request, the PRDS is capable of transmitting the additional pieces of data found in a Military Interdepartmental Purchase Request (MIPR, DD form 448), the MIPR Acceptance (DD-448-2), and other inter/intra-governmental transactions (IGT).' AS DESCRIPTION FROM dual
) src
ON ( tar.ENUM_TYPE = src.ENUM_TYPE  AND tar.ENUM_VALUE = src.ENUM_VALUE ) 
WHEN MATCHED THEN 
    UPDATE SET tar.ENUM_DISPLAY_NAME = src.ENUM_DISPLAY_NAME, tar.DESCRIPTION = src.DESCRIPTION, tar.ENUM_TYPE_REC_ID = src.ENUM_TYPE_REC_ID, tar.ENUM_TYPE_REC_UUID = src.ENUM_TYPE_REC_UUID, tar.ORDER_BY = src.ORDER_BY, tar.CONSTANT_FLAG  = src.CONSTANT_FLAG, tar.REC_ID  = src.REC_ID, tar.REC_UUID  = src.REC_UUID  
WHEN NOT MATCHED THEN 
    INSERT ( tar.ENUM_TYPE, tar.ENUM_VALUE, tar.ENUM_DISPLAY_NAME, tar.DESCRIPTION, tar.ENUM_TYPE_REC_ID, tar.ENUM_TYPE_REC_UUID, tar.ORDER_BY, tar.CONSTANT_FLAG ) 
    VALUES ( src.ENUM_TYPE, src.ENUM_VALUE, src.ENUM_DISPLAY_NAME, src.DESCRIPTION, src.ENUM_TYPE_REC_ID, src.ENUM_TYPE_REC_UUID, src.ORDER_BY, src.CONSTANT_FLAG );

COMMIT;


MERGE INTO authDataSource_dev.EnumValueAssocRef tar USING ( 
SELECT 11 AS rec_id, 'B4038CA1-F30F-2545-9935-16F165CEBDAB' AS rec_uuid, 'ads_source' AS enum_type, 'PRDS_V3.0.0' AS enum_value, 'VERSION' AS enum_assoc_type, '3.0.0' AS enum_assoc_code, 'v3.0.0' AS enum_assoc_name, 'v3.0.0' AS enum_assoc_desc, '192' AS enum_value_rec_id, 'CF3E1E02-E7F3-6F4A-BC29-A4FECD67D158' AS enum_value_rec_uuid FROM dual UNION ALL 
SELECT 12 AS rec_id, '945C1B17-F52E-FA47-8464-755793669C42' AS rec_uuid, 'ads_source' AS enum_type, 'PRDS_V2.0.0' AS enum_value, 'VERSION' AS enum_assoc_type, '2.0.0' AS enum_assoc_code, 'v2.0.0' AS enum_assoc_name, 'v2.0.0' AS enum_assoc_desc, '193' AS enum_value_rec_id, '5A6C588B-D568-164C-A1EF-938E0416D975' AS enum_value_rec_uuid FROM dual UNION ALL 
SELECT 13 AS rec_id, 'FB3FCCD7-FEA0-F045-939B-28518FFE9AA8' AS rec_uuid, 'ads_source' AS enum_type, 'PRDS_V1.1.0' AS enum_value, 'VERSION' AS enum_assoc_type, '1.1.0' AS enum_assoc_code, 'v1.1.0' AS enum_assoc_name, 'v1.1.0' AS enum_assoc_desc, '194' AS enum_value_rec_id, 'FD96A70B-C1B0-8449-BD72-997C33D67315' AS enum_value_rec_uuid FROM dual UNION ALL 
SELECT 14 AS rec_id, '39A41E2C-B9E8-9745-923C-E92CB85C0581' AS rec_uuid, 'ads_source' AS enum_type, 'PRDS_V1.0.2' AS enum_value, 'VERSION' AS enum_assoc_type, '1.0.2' AS enum_assoc_code, 'v1.0.2' AS enum_assoc_name, 'v1.0.2' AS enum_assoc_desc, '195' AS enum_value_rec_id, '3F0652E4-E9A2-3B49-8182-C9B6A22B4CFB' AS enum_value_rec_uuid FROM dual UNION ALL 
SELECT 15 AS rec_id, 'CF61DDBB-72AF-0641-B1F3-97D9184EDC85' AS rec_uuid, 'ads_source' AS enum_type, 'PRDS_V1.0.1' AS enum_value, 'VERSION' AS enum_assoc_type, '1.0.1' AS enum_assoc_code, 'v1.0.1' AS enum_assoc_name, 'v1.0.1' AS enum_assoc_desc, '196' AS enum_value_rec_id, 'C5E999B2-5051-D541-BE69-233F541B265F' AS enum_value_rec_uuid FROM dual UNION ALL 
SELECT 16 AS rec_id, '9F6C714F-90D1-0A40-A45C-77A76A717ACA' AS rec_uuid, 'ads_source' AS enum_type, 'PDS_PhaseII_V2.5.1' AS enum_value, 'VERSION' AS enum_assoc_type, '2.5.1' AS enum_assoc_code, 'v2.5.1' AS enum_assoc_name, 'v2.5.1' AS enum_assoc_desc, '198' AS enum_value_rec_id, 'A5793C2B-520C-8240-82BE-0773C18D1C17' AS enum_value_rec_uuid FROM dual UNION ALL 
SELECT 17 AS rec_id, '5F343DEA-5033-EB44-A839-4AC60A09A170' AS rec_uuid, 'ads_source' AS enum_type, 'PDS_PhaseII_V2.5.0' AS enum_value, 'VERSION' AS enum_assoc_type, '2.5.0' AS enum_assoc_code, 'v2.5.0' AS enum_assoc_name, 'v2.5.0' AS enum_assoc_desc, '199' AS enum_value_rec_id, 'E01A140A-0A14-2A4A-9C25-7F13173533BB' AS enum_value_rec_uuid FROM dual UNION ALL 
SELECT 18 AS rec_id, '18FBA432-6C04-034B-AB2C-966E1AA256CD' AS rec_uuid, 'ads_source' AS enum_type, 'PDS_PhaseII_V2.4.0' AS enum_value, 'VERSION' AS enum_assoc_type, '2.4.0' AS enum_assoc_code, 'v2.4.0' AS enum_assoc_name, 'v2.4.0' AS enum_assoc_desc, '200' AS enum_value_rec_id, 'EE947B23-927D-9B48-8BDE-8D042D05A190' AS enum_value_rec_uuid FROM dual UNION ALL 
SELECT 19 AS rec_id, '844CE1B0-A2FA-3745-849F-E5CDE75D0C09' AS rec_uuid, 'ads_source' AS enum_type, 'PDS_PhaseII_V2.3.0' AS enum_value, 'VERSION' AS enum_assoc_type, '2.3.0' AS enum_assoc_code, 'v2.3.0' AS enum_assoc_name, 'v2.3.0' AS enum_assoc_desc, '201' AS enum_value_rec_id, '7AFB8033-52C4-A044-ACD0-BAA34DFD2FA2' AS enum_value_rec_uuid FROM dual UNION ALL 
SELECT 20 AS rec_id, 'C33022AC-9A98-C448-8714-21F1003D6C20' AS rec_uuid, 'ads_source' AS enum_type, 'PRDS_V1.0.0' AS enum_value, 'VERSION' AS enum_assoc_type, '1.0.0' AS enum_assoc_code, 'v1.0.0' AS enum_assoc_name, 'v1.0.0' AS enum_assoc_desc, '197' AS enum_value_rec_id, '3BE490E2-EF8D-9E46-AB67-3572F97B638C' AS enum_value_rec_uuid FROM dual 
) src 
ON (  tar.enum_type = src.enum_type  AND tar.enum_value = src.enum_value  AND tar.enum_assoc_type = src.enum_assoc_type AND tar.enum_assoc_code = src.enum_assoc_code ) 
WHEN MATCHED THEN 
    UPDATE SET tar.rec_id = src.rec_id, tar.rec_uuid = src.rec_uuid, tar.ENUM_assoc_NAME = src.ENUM_assoc_NAME, tar.enum_assoc_desc = src.enum_assoc_desc, tar.ENUM_value_REC_ID = src.ENUM_value_REC_ID, tar.ENUM_value_REC_UUID = src.ENUM_value_REC_UUID   
WHEN NOT MATCHED THEN 
    INSERT ( tar.enum_type, tar.enum_value, tar.enum_assoc_type, tar.enum_assoc_code, tar.enum_assoc_name, tar.enum_assoc_desc, tar.enum_value_rec_id, tar.enum_value_rec_uuid ) 
    VALUES ( src.enum_type, src.enum_value, src.enum_assoc_type, src.enum_assoc_code, src.enum_assoc_name, src.enum_assoc_desc, src.enum_value_rec_id, src.enum_value_rec_uuid );

COMMIT;
